#+TITLE: 健身跟苦力不是一回事
#+DATE: 2016-12-30
#+TAGS:

#+begin_quote
只有牛逼的人才配谈人生
#+end_quote

今天我破个例，谈谈小时候，我爸常给我讲的两个故事：

- 故事一
#+begin_quote
有个小伙子，捡了地上的一粒米饭吃了，…… ，后来，考起了清华大学。……
#+end_quote

- 故事二
#+begin_quote
有个父亲很有钱，但是他不给过多的钱给自己儿子，假期还让自己儿子去工地搬砖……
#+end_quote

我相信不少农村出来的孩子听过类似的故事，不知你们当时是不是和我一样，对的人生充满希望。然而，这是一个骗局，或许父亲们连自己都骗了。尽管故事一和二的主角最后都有个牛逼的人生，但是从 *普遍性* 看来，故事一的主角是少数现象，社会中，故事二的主角才是真正的社会主角，这些主角一开始就有很好的家庭环境，历练的经验当然也有，却各不一样，但是「搬砖」这种，我就只能笑而不语了。

现在很多电视喜欢讲这种故事，尤其是故事一这类的，而我今天要批评的重点，是故事二这类，故事二这类的很多上了娱乐节目 --- 明星将自己的小孩放到贫穷落后的农村去「体验」一段时间，小孩最终「很配合的逗乐了很多观众」的同时，也安慰了千万农村父母的心 --- 穷还是挺有优势的！

明星小孩的穷养「体验」是加了引号的，就算真正的体验，跟实际境况还是不一样的，体验赚钱的艰辛，并不是真正的贫穷生活。大家很容易理解，健身跟苦力不是一回事；但是在穷养问题上，大家就趋于观察表面现象，和经过特殊抽样的实验结果，最终给自己一个满意的实验结论。为什么说是特殊抽样的，因为得以传播的故事的主角，都是通过努力，成功翻身了的，而实际上，大批穷人努力了，也没有很大的改善；还有更大一批，没有努力去改善，仅仅在过着贫穷的生活而已，这并不是这些人不想改善，而是由于思想认知，资源环境缺失，想要改变，却根本无从下手。

下面做个思想实验，李嘉诚为了让自己的小小儿子体验一下赚钱的艰辛，培养面对逆境的能力，在儿子未成年，经济还未独立的一段时间里，要求儿子自己赚钱吃饭，这种情况下，小伙子来的我的公司，我鉴于我跟李嘉诚的朋友关系（让我小小的想象一下），我跟小伙子安排了一个工作，并付给他小小的一笔时薪（给太多，李哥会不开心的），小伙子来到自家附近的餐厅，想饱吃一顿，却发现钱不够，张老板见状，直接免费给小伙子升级了套餐，毕竟李哥是常客，善待他的儿子，日后有好处的。如果把李嘉诚的儿子换成一个家境贫困的穷小伙，这思想实验顺利进行下去的可能性就不大了。有钱人的穷养体验，那是对技能的培养，不是他们真正的处境，他们实际处在一个充满机会，充满美好人际关系的圈子，有机遇，有帮助。

健身不是苦力，穷养不是穷！努力赚钱，给孩子（自己）提供一个好环境，这才是正解。
