#+TITLE: 我们所说的记忆是什么？
#+DATE: <2017-06-25 Sun>
#+TAGS: 认知

「清醒思考的艺术」里面提到的一个观点很有意思 -- 人们喜欢故事，更容易记住有故事的信息，尽管故事使得信息量增加了。

比如：

「伽罗华死了」

有故事性的版本：

「伽罗华为了心爱的女人，和人决斗，死了」

下面这个版本信息量更大，然而却更容易让人记住。实际上我们的记忆很难消失的，所谓的消失只是找不出来，不然哪来「突然想起」这一说法了。我们的大脑就好比一块硬盘，记忆就像是存储了各种各样的文件，如果不好好整理，文件很容易丢失。

整理电脑文件最简单的方式，就是分门别类，建立文件夹，为文件夹命名，文件夹里面可以细分更多的文件夹，这样我们的文件就不那么容易丢失了。然而，建立文件夹实际上是增加了硬盘的存储空间，和大脑一样，要更容易的找到文件，我们需要创建更多的文件把文件管理起来。:-), 好吧，听起来怪怪的。

文件夹方式管理文件，实际上是一种索引管理的方式， 为信息建立索引，分门别类。文件夹属于一种较为简单的索引方式，比如文件只能属于一个文件夹，然而，计算机的创造者们并没有这么笨，文件还支持「快链」，Windows 桌面的文件不基本都是「快链」吗？所以，文件还是可以属于好几个文件夹的。

人脑记忆的信息里面， 那些是索引，那些是文件？「心爱、决斗、死了」这些抽象词都是，「伽罗华」这种具体的东西就是个文件咯（他到底算不算个东西？好像思考太多了, haha）。而随着我们学习量的增加，抽象层次分的也越来越多，「抽象」和「具体」也变成相对的了，好比，文件夹下面也有文件夹，对上层文件夹来说，把文件夹当做文件也没有错。

现在很好理解为什么人学的越多，记忆力越好的原因了，因为脑容量实在太大了，存储空间人一辈子根本用不完，而学的越多，掌握的抽象概念越多，索引越具体，关联越多，当需要用的时候，查找出来也最快。所以，不要再找借口不学习了，说要把大脑空间留给「有用」的知识了。

大脑容量大不大不是最重要的，善于管理才是关键。实际上， 人的脑容量还没有大猩猩的大，瞬间记忆力也不如大猩猩，然而我们的近亲大猩猩没有抽象能力，不能讲故事，不能管理信息，需要用的时候，大脑不能很好的调出记忆供参考，所以，我们人类创造了「金刚」。


听说狗（AlphaGo）又赢了人，这是个好消息，因为狗没有故意输。
